### ISSUE TITLE
How to get the selected position 

### ISSUE THREAD

**Issue by gbreux** [alfrdmalr/walktour#100]
Hi,
I'd like to know if there is a way to get the selected position from the custom tooltip?

use case:
I'd like to add an arrow to the custom tooltip properly located depending on where it is positionned (south, east, north etc.)

Thanks a lot!

**Comment by alfrdmalr** [comment]
I assume you've been using the `tourLogic` object in your custom tooltip. I can make some changes that will allow me to add the selected orientation (North, South, etc.) to that object, which you can use to decide where/how to render your arrows. Does this suit your needs?

**Comment by gbreux** [comment]
Yes I do use `tourLogic` in my custom tooltip.
That would be awesome! Thanks!

**Comment by gbreux** [comment]
@alfrdmalr Did you have a chance to check the PR I sent for this "issue"?

**Comment by alfrdmalr** [comment]
@gbreux Sorry, I realized I never submitted the review (!). You can find the revision [here](https://github.com/alfrdmalr/walktour/pull/101#discussion_r453734796). Once I have time this week I can implement/merge those changes, but until then I'd love to get an opinion from you on which strategy might work best.

**Comment by alfrdmalr** [comment]
#101 is merged and published as version 5.0.0, so I'm closing this.
