### ISSUE TITLE
How to create a custom mask?

### ISSUE THREAD

**Issue by goodok21** [alfrdmalr/walktour#114]
I need to create a custom mask and it will be good to have any chance to create it, for example to pass new `mask` prop:

```
<Walktour steps={[]} mask={({ positionCoords }) => <div />} />
```

and it will be override default Mask component to render own svg with custom mask.

Thank you 🙏

**Comment by alfrdmalr** [comment]
Would you take a look at #116? I'm hoping this option supports your use case. If it does, I'll go ahead and merge and update the package.

Sorry for the delay on this. I've been pressed for time lately, and there was a massive dependency update that needed to happen before I focused on any new features.

**Comment by goodok21** [comment]
Yes, it will be helpful, thank you so much 👍

**Comment by alfrdmalr** [comment]
This should be all set as of 5.1.1. Thanks for the issue!
