### ISSUE TITLE
[Bug] Scoped Tour Mask/Tooltip Position Update

### ISSUE THREAD

**Issue by hshockley** [alfrdmalr/walktour#96]
In scoped tours, if the size of the container is changed, the mask and tooltip position will not begin to auto update until the next button is clicked to move to the next step. The checkbox in a previous version caused it to only update per click rather than kicking off the size event listeners.

This behavior can be observed in storybook. Increase the width/height and the mask/position will not update. Click 'next step' and it will begin to update

**Comment by alfrdmalr** [comment]
What method are you using to change the size of the container?
And just for completeness, is there a particular story you're looking at that I can use to repro this?

Also, I'm not sure what you're referring to with "The checkbox in a previous version caused it to only update per click rather than kicking off the size event listeners." When you say checkbox, are you talking about one of the knobs on storybook or something else entirely?

**Comment by hshockley** [comment]
The app that is using the tour is sitting in a movable/resizable container. The tour is being handed a ref which contains an observable for the container that emits resizing events. 
Story that I am using to reproduce this: https://alfrdmalr.github.io/walktour/?path=/story/walktour-demo--scoped
You can increase the width/height of the div with the id 'demo-container' to reproduce the behavior.

To clarify the checkbox, I am referring to the previous version of the tooltip in the rocketsoftware/carbon repo which included a checkbox for enabling/disabling the tour. I have attempted to modify some of the useEffect hooks specifically the one that runs on mount to call updateTour.  Where exactly in the updateTour method does the Tour initialize it's listener for custom resize events and does it occur on the mounting of the component?

**Comment by alfrdmalr** [comment]
Obviously I don't have the full context, but changing the size of the container element (I'm assuming via devtools?) won't trigger any resize listeners, unless that functionality has specifically been implemented by the container. So if it's resizable via drag or something, _that_ method of resizing will cause an update to happen - any method that doesn't communicate via _setUpdaterListener_ (devtools) will not.

The resize event listeners are initialized here:
https://github.com/alfrdmalr/walktour/blob/773ad31a5cb9a2b40e701cf29a3a5a3b0a9aeb3e/src/components/Walktour.tsx#L268-L269

The function called looks like this:
https://github.com/alfrdmalr/walktour/blob/773ad31a5cb9a2b40e701cf29a3a5a3b0a9aeb3e/src/utils/tour.ts#L28-L44

Essentially, if there's a custom listener function (and matching removal function) provided, those will be used; if not, the default window resize listener is used.

These listeners are constructed/destroyed each time the tour updates. Technically, they aren't set on mount but instead slightly _after_ mount; the first thing the component does when it mounts is determines where it should spawn a portal. Once that's accomplished (after the first render) then the updateTour method gets called for the first time.

Does that help at all?

**Comment by hshockley** [comment]
Yeah, thanks. It seems to be more that re renders are not occurring at the first and last step of a tour if setUpdateListener setRemoveListener are set. I will keep investigating. Thanks for the help
